PietroProperties/holms.platformclient.net

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/IncidentalItemAvailabilityQuery.cs
- proto/supply/incidental_items/incidental_item_availability_query.proto
@eldavido One last platform hiccup for this ES incidental items change. It's small but I want to run it past you since you've done this supply work.
Adds a field for indicating the currently-held quanitity of an incidental
reservation in the case of an availability query for an amendment to that reservation. Currently the
availability query is loading the reservation from the database, which is
not possible/hygenic with ES incidental reservations.
> Adds existing held quantity to availability query

- csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/ApplicationClient.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/IApplicationClient.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/MockApplicationClient.cs
Done to remove heartache caused by NAT drops, etc. by using a channel that
sits inactive for ~1hr between uses.
> Remove persistent login channel.

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GuestSvc.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GuestSvcGrpc.cs
- proto/crm/rpc/guest_svc.proto
This adds the service endpoint for "search for all guests with a provided email address". The backing implementation will be in application.
The higher-level goal is to enable association of a quasi-anonymous "web booker" with a previous guest, based on their supplied email address.
[#133051095]
> Add search by email endpoint to guest service

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CompleteOpenReservation.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
- proto/booking/reservations/complete_open_reservation.proto
- proto/booking/reservations/reservation_summary.proto
@eldavido PTAL
This adds information onto summary and complete reservation DTOs about the room occupancy status.
My plan is that the occupied room will be stored in materialized state as a room number string and an indicator (guid in the database) on the reservation model object. I'm calling this current-or-terminal occupancy because we have mutually-exclusive cases where we want to know the room occupancy of the reservation:
1) Upon observing a checked-in reservation, we wish to know the room it currently occupies
2) Upon observing a checked-out reservation, we wish to know the last room it occupied
These two cases occur in mutual exclusivity because occupancy is hard-released on checkout. Therefore, I decided to merge them into one field because,
1) It's simpler just to leave the field …
> Adds current-or-terminal-occupied-room to dtos

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/LodgingBookingSvc.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/LodgingBookingSvcGrpc.cs
- proto/booking/rpc/lodging_booking_svc.proto
Endpoint used by the client for getting departure information of a list of occupied rooms so the client can signal which rooms are departing and which are staying over.
> Adds endpoint for retreiving reservation summaries

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CheckInService.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CheckInServiceGrpc.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/OpenLodgingReservationSvcGrpc.cs
- proto/booking/rpc/check_in_service.proto
- proto/booking/rpc/open_lodging_reservation_svc.proto
@eldavido PTAL
Get/Set endpoints for pre-checkin information.
Pre-checkin info lumped together with recommended authorization amounts. I moved the endpoint to the check-in service and marked the old recommended authorization amounts obsolete. We can delete it once everything is moved to the new endpoint so we don't sit on any breaking changes in platform.
> Adds vehicle plate and personal identification endpoints

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomOccupancyChangedNotification.cs
- proto/operations/rooms/room_occupancy_changed_notification.proto
Default-false boolean "occupancy_prematerialized_on_reservation". The
default case is that occupying a room will trigger this rabbit message,
which is picked up by booking to materialize occupancy state on the
reservation.
The non-default is for cases where we're occupying a room as part of a check-in, the check-in
transaction will materialize the occupancy state onto the reservation, in
order to avoid a race condition between the occupancy materialization and
the check-in transaction.
There are no grpc changes here because the public API should not expose
this option to not materialize state onto the reservation, and should be
a private interface within the HOLMS Application ecosystem.
> Adds field on room occupancy changed notification

- csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.csproj
- csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.nuget.targets
- csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOExtensions/TenancyConfig/PropertyExtensions.cs
@eldavido PTAL
This is in service of: https://www.pivotaltracker.com/story/show/133867523
This logic was originally on the Property model object. The problem is that we often don't have access to the property object and I'd rather not have to round trip to the application service to figure out opsdate conversions. I consider opsdates as a more fundamental concept than our model.
> [#133867523] Adds opsdate conversions to support

- csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOBuilders/Operations/MailboxEntryBuilder.cs
[#136141653]
https://www.pivotaltracker.com/story/show/136141653
Somewhere along the way, someone encountered an issue with a null in proto and decided the solution was to prevent nulls. There are currently 2 use cases for the mailbox entry builder: 
1. StaffMsgSvc - The StaffMsgSvc grabs the mailbox entries for the current users and uses the mailbox entry builder to create them. In this case the sender is populated.
2. LodgeIC - New Message (brand new or reply / forward). LodgeIC just hits the server endpoint when actually sending the message, and the server assigns the sender based on the current user. It ignores the sender field.
Neither of these cases require that the sender be not null. This might fix the entire bug, but once this is approved, I'll get it into application / lodgeic …
> Removes requirement for non-null sender in mailboxentry builder.

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardMerchant.cs
- proto/money/cards/card_merchant.proto
[#131823325]
Should have made these three int32s instead of strings the first time to align with portico sdk.
> Updates CardMerchant to use int32 where appropriate.

- csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.csproj
- csharp/HOLMS.Platform/HOLMS.Platform/Support/ReservationTags/CompStayTag.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Support/ReservationTags/MigratedReservationTag.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Support/ReservationTags/ReservationTagBase.cs
@laxderek - adding this to allow reservations to be marked as part of the migration.
If a reservation is part of the migration, and it was created earlier than a certain date, we treat it as guaranteed, so that we don't have a whole stack of unguaranteed reservations going back ages.
I want to get to the point where a reservation's guarantee state conveys useful information about the state of the property, and is something a GSA can proactively try to fix, rather than having hundreds of them floating around all the time.
> Add tag for migrated reservations

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationPriceEstimate.cs
- proto/booking/pricing/reservation_price_estimate.proto
The pricing array is the pre-tax provided subtotals for a stay, while the
original pricing array maintains its representaiton of "actual" subtotals
> Adds a second pricing array to rpe

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CompleteOpenReservation.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
- proto/booking/reservations/complete_open_reservation.proto
- proto/booking/reservations/reservation_summary.proto
With reservation now determining which cancellation policy to use based on
channel, the reservation dtos should include the cancellation policy that
the reservation is using to de-duplicate the business logic that
determines this.
> [#141723839] Adds cancellation policies to reservations

- csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.nuget.targets
- csharp/HOLMS.Platform/HOLMS.Platform/Support/ReservationTags/ImmutableTagSet.cs
This makes initializing a ReservationTagBase more convenient, as sometimes
the incoming list is empty.
> Allow passing a null IEnumerable<ReservationTagBase>

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardAuthorizationPurpose.cs
- proto/money/cards/card_authorization_purpose.proto
Adds flag used when paying a penalty.
This gets interpreted by the heartland processor facade to trigger some special behaviors on the "lodging edit data", namely, to mark a no-show and change the lodging checkin/checkout behavior.
> Add penalty payment flag

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/AccountingTxnSvc.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/AccountingTxnSvcGrpc.cs
- proto/money/rpc/accounting_txn_svc.proto
@eldavido PTAL
This is some cleanup on the IIF export interface. We no longer return the IIF string to the scheduler, because it's getting uploaded directly from the app server.
App server also will be handling tracking the last IIF export, with the option to ignore (used for manual export).
> Consolodates IIF export into single endpoint

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ProcessorTransactionResult.cs
- proto/money/cards/transactions/processor_transaction_result.proto
Used when the gateway signals that the original transaction is invalid.
This is distinct from an invalid request.
> [#14780565] Adds a processor txn response

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
- proto/booking/reservations/reservation_summary.proto
The number of outstanding room keys for a reservation gets added to the
reservation summary. This number is tracked by events, but stored as a
queriable field on the model.
The value of this is that PMC wants on its departure report a count of the number
of keys they expect a guest to have.
> [#149452341] Adds outstanding room keys to res summary

- csharp/HOLMS.Platform/HOLMS.Platform/Support/ReservationTags/TaxExemptTag.cs
Old tax-exempt tags were arriving as "te:", causing string.Split() to
yield 2-element array with the second element as null.
Corrects the constructor to accomodate this.
> [#149940625] Fixes tag compatability

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/OpenLodgingReservationSvc.cs
- proto/booking/rpc/open_lodging_reservation_svc.proto
https://www.pivotaltracker.com/story/show/154384314
Adds folio events to the reservation history response. The folio will be responsible for populating its own list of history in order to constrain knowledge of the folio events.
> [#154384314] Add folio events to res history

- csharp/HOLMS.Platform/HOLMS.Platform/Support/Currency/DollarCents.cs
@eldavido PTAL
Turns out you had a unary - operator, but it was hidden. I refactored it and put it with the rest of the operators.
> Adds unary + operator and refactors - unary operator

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardProcessingSvc.cs
- proto/money/rpc/card_processing_svc.proto
Previously, we took a calendar date range, but we really just want a UTC-specified range - get that from the client, rather than two dates.
> Convert to client specification of batch search date range

- csharp/HOLMS.Platform/HOLMS.Platform/Support/Time/InclusiveDateRange.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomClaimsSvc.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomWithClaimInfo.cs
- proto/operations/rooms/room_with_claim_info.proto
- proto/operations/rpc/room_claims_svc.proto
Simplifies and reworks how we calculate whether we can assign rooms. It used to be based on occupancy, but what we wanted is assignment. More of the calculation is shifted server-side, making it easier for the client to consume.
[#154909059]
> Clean up reservation room claim assignments.

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/OpenLodgingReservationSvc.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/OpenLodgingReservationSvcGrpc.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
- proto/booking/reservations/reservation_summary.proto
- proto/booking/rpc/open_lodging_reservation_svc.proto
https://www.pivotaltracker.com/story/show/145089111
@eldavido PTAL
I decided not to add additional guests to reservation summary. We have one use case for it, and I'm concerned that it'll add a significant performance hit to every other use case.
Instead I'll just have the UI grab RAPs for in-house reservations and join in the fetcher.
> [#145089111] multi-rap get

- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomTypeSvc.cs
- csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomTypeSvcGrpc.cs
- proto/supply/rpc/room_type_svc.proto
Happens when base holds are adjusted down, which causes overall holds to
go negative.
[#157580319]
> Allow platform to signal that room type update was rejected.
