PietroProperties/holms.platformclient.net

.gitignore
csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/JWToken.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/StubSecurityKeyFactory.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/ValidatedJWToken.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/ValidatedJWTokenTestForgery.cs
csharp/HOLMS.Platform/HOLMS.Platform/project.json
csharp/HOLMS.Platform/HOLMS.Platform/project.lock.json

Removes static key specification methods. Software engineering FTW

Remove static JWT security key

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CancelledReservation.cs
proto/booking/reservations/cancelled_reservation.proto

[#133070447]
https://www.pivotaltracker.com/story/show/133070447

Adds RequestingParty to cancelled reservation

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOBuilders/Premises/RoomTypeBuilder.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GuestCompletedStay.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/IncidentalSupplySvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ItemHoldCreationResponse.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ItemHoldUpdateResponse.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomType.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/SessionContext.cs
csharp/HOLMS.Platform/HOLMS.Platform/project.lock.json
proto/crm/guests/guest_completed_stay.proto
proto/primitive/session_context.proto
proto/supply/incidental_items/item_hold_creation_response.proto
proto/supply/incidental_items/item_hold_update_response.proto
proto/supply/room_types/room_type.proto
proto/supply/rpc/incidental_supply_svc.proto

[#132774037]
https://www.pivotaltracker.com/story/show/132774037

Removes web fields from room type.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CorrespondenceSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CorrespondenceSvcGrpc.cs
proto/crm/rpc/correspondence_svc.proto

@eldavido PTAL, not much to see. Just an endpoint for printing confirmation letters.

Adds confirmation letter printing endpoint

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
proto/booking/reservations/reservation_summary.proto

Adds group booking id to reservation summary.

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/JWToken.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/ValidatedJWToken.cs

This prevents duplicate token issuance
[#134016151]

Add nonce to JWTs

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/IncidentalItemReservationSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/IncidentalItemReservationSvcGrpc.cs
proto/booking/rpc/incidental_item_reservation_svc.proto

Adds required reservation indicator to drop reservation

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/SessionSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/SessionSvcGrpc.cs
proto/iam/rpc/session_svc.proto

[#134183943]
https://www.pivotaltracker.com/story/show/134183943

Adds Logout endpoint to session service.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CompleteOpenReservation.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/OpenLodgingReservationSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/OpenLodgingReservationSvcGrpc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
proto/booking/reservations/complete_open_reservation.proto
proto/booking/reservations/reservation_summary.proto
proto/booking/rpc/open_lodging_reservation_svc.proto

https://www.pivotaltracker.com/story/show/133973527
Endpoint for updating vehicle information on a reservation. We need this to be able to use the vehicle report in any capacity beyond academic.
Self-reviewing since this is a small non-breaking change.

Adds endpoint for updating vehicle information

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrontDeskReportingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrontDeskReportingSvcGrpc.cs
proto/reporting/rpc/front_desk_reporting_svc.proto

Pretty straight-ahead, just adds an endpoint to our well-established front desk service.
h/t @pcsouza for laying down some great early work here.
[#133973539]

Add "get reservation credit report" endpoint to reporting service

---

csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/ApplicationClient.cs

[#134183943]
https://www.pivotaltracker.com/story/show/134183943

Adds automatic logout as part of Application Client shutdown path.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CancelledReservation.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrontDeskReportingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrontDeskReportingSvcGrpc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationCancellationSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationCancellationSvcGrpc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
proto/booking/reservations/cancelled_reservation.proto
proto/booking/reservations/reservation_summary.proto
proto/booking/rpc/reservation_cancellation_svc.proto
proto/reporting/rpc/front_desk_reporting_svc.proto

Adds SearchCancelledReservations endpoint to CancellationSvc.
[#133973569]
https://www.pivotaltracker.com/story/show/133973569

Adds CancellationDate to CancelledReservation DTO.

---

csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/ApplicationClient.cs

[#134183943]
https://www.pivotaltracker.com/story/show/134183943

Makes logout call synchronous.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GenesisBookingResult.cs
proto/booking/reservations/genesis_booking_result.proto

[#135179027]
https://www.pivotaltracker.com/story/show/135179027

Adds invalid booking result.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrontDeskReportingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrontDeskReportingSvcGrpc.cs
proto/reporting/rpc/front_desk_reporting_svc.proto

Adds another endpoint...not much to see here.
[#133973611]

Add general availability report request endpoint

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationState.cs
proto/booking/reservations/reservation_state.proto

@eldavido PTAL
https://www.pivotaltracker.com/story/show/134742143

Removes no-show and genesis reservation states

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FolioChargePostedNotification.cs
proto/booking/folio_charge_posted_notification.proto

[#132011375]
https://www.pivotaltracker.com/story/show/132011375

Adds ReservationId to FolioChargePostedNotification.

---

csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/MockApplicationClient.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/AccountingTransaction.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CheckInService.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CheckInServiceGrpc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrontDeskReportingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrontDeskReportingSvcGrpc.cs
proto/money/accounting/accounting_transaction.proto
proto/reporting/rpc/front_desk_reporting_svc.proto

Also, some attempt to normalize the request/response types for the various
folio reports: charge/credit, payments.
[#133973615]

Add "get folio payment report" endpoint.

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/JWToken.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/ValidatedJWToken.cs

[#134825047]
https://www.pivotaltracker.com/story/show/134825047

Stores the enum string instead of int for JWT Security Actions.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportingSvcGrpc.cs
proto/reporting/rpc/management_reporting_svc.proto

Add GL Distribution Report endpoint

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrpAmendmentResponse.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GenesisBookingResult.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationPriceEstimate.cs
proto/booking/pricing/reservation_price_estimate.proto
proto/booking/reservations/frp_amendment_response.proto
proto/booking/reservations/genesis_booking_result.proto

Added to price estimate
FRP Amendment
Genesis Booking
Done in response to https://github.com/shortbar/holms/pull/867#pullrequestreview-12540004

Adds MLOS/CTA responses

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportManifests.cs
proto/reporting/input_params/management_report_manifests.proto

@eldavido Adds lodging verification report to manifest

Adds lodging verification report to manifest

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardMerchant.cs
proto/money/cards/card_merchant.proto

[#131823325]
https://www.pivotaltracker.com/story/show/131823325
**This is a breaking change**

Updates CardMerchant to handle terminal credentials.

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/ReservationTags/ReservationTagBase.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingSvcGrpc.cs
proto/booking/rpc/group_booking_svc.proto

Adds service ednpoint for retrieving reservations by group booking tag
Adds descriptor array method to ReservationTagBase
@eldavido PTAL

Adds service endpoint [#136467835]

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomType.cs
proto/supply/room_types/room_type.proto

[#136828615]
https://www.pivotaltracker.com/story/show/136828615
Not a breaking change.

Adds name field to room_type.

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOBuilders/Premises/RoomBuilder.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOBuilders/Premises/RoomTypeBuilder.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GuestCheckedIn.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/Room.cs
proto/crm/guests/guest_checked_in.proto
proto/operations/rooms/room.proto

Updates field on room to room_type_name instead of description.
Updates builders where appropriate.
[#137658071]
https://www.pivotaltracker.com/story/show/137658071
https://www.pivotaltracker.com/story/show/136968927

Adds RoomType to guest history summary.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioSvcGrpc.cs
proto/money/rpc/reservation_folio_svc.proto

@eldavido PTAL
https://www.pivotaltracker.com/story/show/135654527

[#135654527] Adds void authorization request

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingSvcGrpc.cs
proto/booking/rpc/group_booking_svc.proto

@eldavido PTAL. Adds "get by id" for group bookings.

Adds get by id endpoints to group bookings svc

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOBuilders/Booking/Groups/GroupBookingBuilder.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBooking.cs
proto/booking/groups/group_booking.proto

Adds some human-readability innate to the group booking by materializing the group name on the group booking DTO.

Adds group name to group booking DTO

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/Property.cs
proto/tenancy_config/property.proto

[#138983527]
https://www.pivotaltracker.com/story/show/138983527

Adds BookingPrefix to property.

---

csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/ApplicationClient.cs
csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/IApplicationClient.cs
csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/MockApplicationClient.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOBuilders/Booking/Groups/GroupBookingBuilder.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBooking.cs
proto/booking/groups/group_booking.proto

[#137986751]
https://www.pivotaltracker.com/story/show/137986751

Removes house account from group booking.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CancelledReservation.cs
proto/booking/reservations/cancelled_reservation.proto

[#135656527]
https://www.pivotaltracker.com/story/show/135656527

Adds cancellation number to cancelled reservation.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomType.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomTypeSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomTypeSvcGrpc.cs
proto/supply/room_types/room_type.proto
proto/supply/rpc/room_type_svc.proto

Adds channel manager id to room type DTO, and room type service

Add id for channel manager (ChannelRUSH) room type DTO

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MerchantAuthorization.cs
proto/money/cards/merchant_authorization.proto

[#139907577]
https://www.pivotaltracker.com/story/show/139907577

Adds HostReferenceNumber and EntryMethod to MerchantAuthorization.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MerchantAuthorization.cs
proto/money/cards/merchant_authorization.proto

Updates EntryMethod options from POSLink API.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingFolioSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingFolioSvcGrpc.cs
proto/money/rpc/group_booking_folio_svc.proto

[#139891873]
https://www.pivotaltracker.com/story/show/139891873

Adds ChargeCorrections to GroupBookingFolioSvc.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/NotPresentPaymentCard.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/TokenizedPaymentCard.cs
proto/money/cards/not_present_payment_card.proto
proto/money/cards/tokenized_payment_card.proto

https://www.pivotaltracker.com/story/show/138683723
HOLMS.Platform support for virtual cards

Adds virtualcard fields [#138683723]

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CorrespondenceSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CorrespondenceSvcGrpc.cs
proto/crm/rpc/correspondence_svc.proto

[#139891647]
https://www.pivotaltracker.com/story/show/139891647

Adds GroupBookingFolio endpoints to CorrespondenceSvc.

---

csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.csproj
csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.nuget.targets
csharp/HOLMS.Platform/HOLMS.Platform/Support/ReservationTags/ReservationTagBase.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/ReservationTags/TaxExemptTag.cs

https://www.pivotaltracker.com/story/show/141109373

Creates tax-exempt tag

---

csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/MockApplicationClient.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOBuilders/Booking/IncidentalReservations/IncidentalAvailabilityRequestBuilder.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/Account.cs
proto/money/accounting/account.proto

Corrects a couple missed instances of inventory item.

---

csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.nuget.targets
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardMerchant.cs
proto/money/cards/card_merchant.proto

[#139908611]
https://www.pivotaltracker.com/story/show/139908611

Adds DebugLogging to card merchant.

---

csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.nuget.targets
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PostedPayment.cs
proto/money/folio/posted_payment.proto

[#139907577]
https://www.pivotaltracker.com/story/show/139907577
I want to get a bit more optional info into the posted payment for CC payments.

Adds optional fields to posted_payment for credit card payments.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardProcessingSvc.cs
proto/money/rpc/card_processing_svc.proto

Small change: adds card indicator to card verification/tokenization request.
Somewhat surprisingly, I need this for the migration.

Add card indicator to card verification request

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PostedRefund.cs
proto/money/folio/posted_refund.proto

[#141053443]
https://www.pivotaltracker.com/story/show/141053443

Adds approval code to posted refund.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioSvc.cs
proto/money/rpc/reservation_folio_svc.proto

Add description to refund request.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MerchantAuthorization.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PostedCardAuthorization.cs
proto/money/cards/merchant_authorization.proto
proto/money/folio/posted_card_authorization.proto

[#139907577]
https://www.pivotaltracker.com/story/show/139907577

Adds details to posted_card_authorization for hps certification.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportManifests.cs
proto/reporting/input_params/management_report_manifests.proto

Adds comp stay to daily reports

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PostedCardAuthorization.cs
proto/money/folio/posted_card_authorization.proto

Adds emv details to posted authorization.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingFolioSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingFolioSvcGrpc.cs
proto/money/rpc/group_booking_folio_svc.proto

[#141724337]
https://www.pivotaltracker.com/story/show/141724337

Group Booking Folio Svc add MiscChargeCorrection.

---

csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/ApplicationClient.cs

I need to be able to end a session when a user logs out. 
I could just call `Dispose`, but decided to use this method as it's named more intentionally.

Extract EndSession method from application client

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ChannelManagerConfig.cs
proto/tenancy_config/channel_manager_config.proto

Self-reviewing as this is a small non-breaking change

Adds disable amendment and cancellation fields

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PostedCardAuthorization.cs
proto/money/folio/posted_card_authorization.proto

Adds AID to posted_card_auth.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSearchSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSearchSvcGrpc.cs
proto/booking/rpc/reservation_search_svc.proto

Add "magical" reservation search with single string argument

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PropertyEmailSenderConfig.cs
proto/tenancy_config/property_email_sender_config.proto

@eldavido PTAL 
https://www.pivotaltracker.com/story/show/143813159

[#143813159] Adds global disable to automated e-mails

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/IifExportConfiguration.cs
proto/money/accounting/iif_export_configuration.proto

https://www.pivotaltracker.com/story/show/143996463
Asset account export disable flag

[#143996463] Adds disable export flag

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MerchantBatch.cs
proto/money/cards/transactions/merchant_batch.proto

[#144906371]
I'm honestly not sure how this happened in the first place. Definitely not the correct solution. This is a breaking change, with 1 usage in holms, and 1 in lodgeic.

MerchantBatch uses timestamp instead of string for date.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
proto/booking/reservations/reservation_summary.proto

[#145300353]
Per your comment:
https://github.com/shortbar/holms.lodgeic/pull/160#discussion_r117622105

Adds creation date to reservation summary.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MasterFolioSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MasterFolioSvcGrpc.cs
proto/money/rpc/master_folio_svc.proto

[#145300617]
https://www.pivotaltracker.com/story/show/145300617

Adds master folio fetch endpoint.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MasterFolioSvc.cs
proto/money/rpc/master_folio_svc.proto

Adds queried_folio to master folio assignment.

---

csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.nuget.targets
csharp/HOLMS.Platform/HOLMS.Platform/Types/Topics/BookingContextTopics.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/Topics/MoneyContextTopics.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/Topics/OperationsContextTopics.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/Topics/PBXConnectorTopics.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/Topics/SupplyContextTopics.cs

Also took this chance to clean up some busted namespacing that's still
lingering after our three-way duct tape job of ApplicationClient, Types,
and Messaging into this library.
[#145367677]

Update event to note save of group booking, not just quantity

---

csharp/HOLMS.Platform/HOLMS.Platform/.gitignore
csharp/HOLMS.Platform/HOLMS.Platform/HOLMS.Platform.nuget.targets
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardProcessorIndicator.cs
csharp/build.bat
proto/money/cards/card_processor_indicator.proto

[#146338877]
https://www.pivotaltracker.com/story/show/146338877

Adds HPS tokenization card processor.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/Property.cs
proto/tenancy_config/property.proto

[#146412041]
https://www.pivotaltracker.com/story/show/146412041

Adds no show delay to property.

---

csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/MockApplicationClient.cs

Finally time to get some mileage out of this thing

Add some mocks to the MockApplicationClient

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MerchantBatch.cs
proto/money/cards/transactions/merchant_batch.proto

[#146409049]
The sequence number is not the correct field to be using here.

Updates batch id name.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardMerchant.cs
proto/money/cards/card_merchant.proto

[#148157019]
https://www.pivotaltracker.com/story/show/148157019

Adds DeveloperId and VersionId.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrpAmendmentResponse.cs
proto/booking/reservations/frp_amendment_response.proto

[#146329613]
https://www.pivotaltracker.com/story/show/146329613

Adds failure response for changed property.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/Room.cs
proto/operations/rooms/room.proto

https://www.pivotaltracker.com/story/show/149452199

[#149452199] Adds kcr room config field

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomSvcGrpc.cs
proto/operations/rpc/room_svc.proto

https://www.pivotaltracker.com/story/show/149452273

[#149452273] Issue room key svc endpoint

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ForeignProperty.cs
proto/tenancy_config/foreign_property.proto

This is a distinct URL field for accessing the booking website, as opposed to the weborch API.
I'd appreciate any input on naming.

Adds a URL field for the booking website

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/StaffSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/StaffSvcGrpc.cs
proto/iam/rpc/staff_svc.proto

[#146729437]
https://www.pivotaltracker.com/story/show/146729437
Let me know what you think. My approach should be pretty straightforward given the code changes.

Updates StaffSvc to return failure info.

---

.gitignore
csharp/HOLMS.Platform/HOLMS.Platform.Tests/HOLMS.Platform.Tests.csproj
csharp/HOLMS.Platform/HOLMS.Platform.Tests/JWTokenTests.cs
csharp/HOLMS.Platform/HOLMS.Platform.Tests/Properties/AssemblyInfo.cs
csharp/HOLMS.Platform/HOLMS.Platform.Tests/Support/SecurityActionFactory.cs
csharp/HOLMS.Platform/HOLMS.Platform.Tests/Support/SeedGuidFactory.cs
csharp/HOLMS.Platform/HOLMS.Platform.Tests/Tests/JWTokenTests.cs
csharp/HOLMS.Platform/HOLMS.Platform.Tests/app.config
csharp/HOLMS.Platform/HOLMS.Platform.Tests/packages.config
csharp/HOLMS.Platform/HOLMS.Platform.sln
csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/ValidatedJWToken.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/Security/ValidatedJWTokenTestForgery.cs

[#151203365]
Adds a test project for writing nunit tests for HOLMS.Platform
Adds tests for jwtoken expiration times

Fixes timezone sensitivity in jwtoken

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/AccountSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/AccountSvcGrpc.cs
proto/money/rpc/account_svc.proto

[#151482155]
https://www.pivotaltracker.com/story/show/151482155

Updates delete response for AccountSvc.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PostedPayment.cs
proto/money/folio/posted_payment.proto

[#135102193]
per https://pietromanagement.atlassian.net/wiki/spaces/LOD/pages/42074113/Payment+Cancellations?focusedCommentId=45449273#comment-45449273

Adds IsCancellable to posted payments.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PostedPayment.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioSvcGrpc.cs
proto/folio/posted_payment.proto
proto/folio/rpc/reservation_folio_svc.proto

Adds CancelPayment rpc endpoint.
[#135102193]
https://www.pivotaltracker.com/story/show/135102193

Adds CardSaleIndicator to PostedPayment

---

csharp/HOLMS.Platform/HOLMS.Platform/Application.Client/MockApplicationClient.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/OperationsReportingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/OperationsReportingSvcGrpc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/Tenancy.cs
proto/iam/tenancy.proto
proto/reporting/rpc/operations_reporting_svc.proto

Moves email for opex email to tenancy.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/Tenancy.cs
proto/iam/tenancy.proto

[#151690403]
https://www.pivotaltracker.com/story/show/151690403

Adds postmark info at the tenancy level.

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardMerchant.cs
proto/money/cards/card_merchant.proto

[#151556090]
https://www.pivotaltracker.com/story/show/151556090

Adds suppress authorizations to card merchant.

---

csharp/HOLMS.Platform/HOLMS.Platform.Tests/Tests/ReservationTagBaseTests.cs

THANKS @pcsouza for making the test project :)

Re-enable tests commented out due to lack of test project

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PretaxReservationQuote.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/TaxedReservationQuote.cs
proto/booking/pricing/pretax_reservation_quote.proto
proto/folio/taxed_reservation_quote.proto

@eldavido PTAL
Per slack discussion, adds tags to quotes. I also added it to the taxed quote since the envisioning of this object is that it will be used by the folio, so it makes sense to pass the tags with it.

[#152130225] Adds tags to pretax/taxed quotes

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/PretaxIncidentalReservationNightlyQuote.cs
proto/booking/pricing/pretax_incidental_reservation_nightly_quote.proto

Self-assigning due to triviality of change.

Adds missing opsdate on pretax_incidental_reservation_nightly_quote

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioSvcGrpc.cs
proto/folio/rpc/reservation_folio_svc.proto

Add new folio state endpoint

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FolioCardSale.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FolioGuestPaymentCard.cs
proto/folio/fsv2/folio_card_sale.proto
proto/folio/fsv2/folio_guest_payment_card.proto

Add missing required info to folio card sale (AID, etc.)

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/Currency/DecimalDollars.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/Currency/DollarCents.cs
csharp/HOLMS.Platform/HOLMS.Platform/Support/Currency/Extensions.cs

Linq-style summation extensions for dollarcents and decimaldollars

Adds sum functions for money types

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationCancellationNotification.cs
proto/booking/reservations/reservation_cancellation_notification.proto

Convert cancellation bool to explicit penalty amount (money)

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FolioStateV2.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MasterFolioSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MasterFolioSvcGrpc.cs
proto/folio/fsv2/folio_state_v2.proto
proto/folio/rpc/master_folio_svc.proto

Also adds a bit of mf-accrual behavior information to folio state
This is helpful in driving the master folio UI

Removes dead endpoints from master folio service

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationBookedNotification.cs
proto/booking/reservations/reservation_booked_notification.proto

@eldavido PTAL. This is in service of updating group booking reservation folios with MF status.

Adds summary to genesis notification

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FolioCardRefund.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FolioCardSale.cs
proto/folio/folio_card_refund.proto
proto/folio/folio_card_sale.proto

Add responsible staff member indicator to folio state refunds and card sales.
[#149938257]

Restore gross folio charges

---

csharp/HOLMS.Platform/HOLMS.Platform.sln
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CompleteOpenReservation.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
proto/booking/reservations/complete_open_reservation.proto
proto/booking/reservations/reservation_summary.proto

https://www.pivotaltracker.com/story/show/154042547

[#154042547] Removes reservation guarantee from dto

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/Currency/DollarCents.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioState.cs
proto/folio/reservation_folio_state.proto

[#154042547] Adds required guarantee tender to folio state

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportManifests.cs
proto/reporting/input_params/management_report_manifests.proto

Add request for planned lodging revenue by source

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportManifests.cs
proto/reporting/input_params/management_report_manifests.proto

Move revenue by source to opsdate, rather than clock-time based

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSearchSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSearchSvcGrpc.cs
proto/booking/rpc/reservation_search_svc.proto

Add "include cancelled" as search parameter for reservations

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/Account.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/AccountingTransaction.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportManifests.cs
proto/money/accounting/account.proto
proto/money/accounting/accounting_transaction.proto
proto/reporting/input_params/management_report_manifests.proto

Also, remove some no-longer-used money/accounting bits.
[#114700781]

Add property statistics report

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationNote.cs
proto/booking/reservations/reservation_note.proto

https://www.pivotaltracker.com/story/show/112193131

[#112193131] Add optional guest property to reservationnote

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportManifests.cs
proto/reporting/input_params/management_report_manifests.proto

Add several date ranges for the property statistics report.
https://www.pivotaltracker.com/story/show/112193131
[#114700781]

Adds property stats requests to current time mgmt report manifest

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioCloseNotification.cs
proto/folio/reservation_folio_close_notification.proto

@eldavido PTAL small amendment to prior platform PR.

[#154650718] Adds invoiced range for folio close notification

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CompleteOpenReservation.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationSummary.cs
proto/booking/reservations/complete_open_reservation.proto
proto/booking/reservations/reservation_summary.proto

This allows seeing whether a pre-checkin reservation has an assigned room.
[#151556446]

Add independent tracking/materialization of "first assigned night"

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ManagementReportingSvcGrpc.cs
proto/reporting/rpc/management_reporting_svc.proto

@eldavido PTAL Adds an endpoint for: https://www.pivotaltracker.com/story/show/113592267

[#113592267] Add endpoint for hk management report

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationGuaranteeSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationGuaranteeSvcGrpc.cs
proto/folio/rpc/reservation_guarantee_svc.proto

Guarantee text should be conditional - auth vs. verify

---

proto/money/cards/customer_payment_card_type.proto

https://www.pivotaltracker.com/story/show/146959857

Adds folio payment card type

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CorrespondenceSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CorrespondenceSvcGrpc.cs
proto/crm/rpc/correspondence_svc.proto

@eldavido https://www.pivotaltracker.com/story/show/156738535
Adds responses to the correspondence service for sending emails. This is so we can inform users of issues with sending e-mail correspondence.

[#156738535] Add responses for sending an email

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FolioCardSale.cs
proto/folio/folio_card_sale.proto

Raw authorized is the last amount the sale was authorized for before
regardless of the sale's state.

[#156819342] Add Raw Authorized to FolioCardSale

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardCaptureReportingSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CorrespondenceSvcGrpc.cs
proto/crm/rpc/correspondence_svc.proto
proto/reporting/rpc/card_capture_reporting_svc.proto

Previously, it used a date range, but we want enumerated batch selection.
[#156775411]

Parameterize closed batches report on enumerated batches

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationPriceOverrideNotification.cs
proto/booking/pricing/reservation_price_override_notification.proto

This is to allow rabbit mount to call the guarantee update method
https://www.pivotaltracker.com/story/show/156748664

[#156748664] Adds quote to price override notification

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOBuilders/Operations/RoomBuilder.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/Room.cs
proto/operations/rooms/room.proto

on room DTO builder:
Remove legacy "MaintenanceState"
Add "MaintenanceStatev2" that's a "pure" maintenance state - clean, dirty, maid in room
Add maintenance request

Remove legacy maintenance state from room

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardProcessingSvc.cs
proto/money/rpc/card_processing_svc.proto

@eldavido PTAL
We need the reservation folio indicator for tokenizing guest cards in case its a virtual card and we need to store it on the folio

[#146959857] Adds res/folio indicator to tokenize request

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CardProcessingSvcGrpc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/KabaEncoderConfig.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/MiwaEncoderConfig.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomSvc.cs
proto/operations/rpc/room_svc.proto
proto/tenancy_config/kaba_encoder_config.proto
proto/tenancy_config/miwa_encoder_config.proto

@eldavido PTAL
This lets the client specify the terminal number and removes terminal number from the configurations.
https://www.pivotaltracker.com/story/show/158009410

[#158009410] Moves terminal number to keycard request

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/DepartureDateCheckoutAcceptibility.cs
proto/booking/checkout/departure_date_checkout_acceptibility.proto

It's just overdue, or on-time
[#157408730]

Remove obsolete "tardy" state

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/CheckoutCandidateViability.cs
proto/booking/checkout/checkout_candidate_viability.proto

This gets displayed to the user in LodgeIC for amendment
[#157408730]

Add "effective checkout date" to viability message

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingFolioState.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/ReservationFolioState.cs
proto/folio/group_booking_folio_state.proto
proto/folio/reservation_folio_state.proto

Platform changes for adding new field maxrefund in reservation folio  state and group booking folio state.
for staroy : https://www.pivotaltracker.com/n/projects/1105748/stories/165040996/comments/201929131

Refund lodgic platform

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/FrontDeskReportManifests.cs
proto/reporting/input_params/front_desk_report_manifests.proto

Platform code review request for the story https://www.pivotaltracker.com/n/projects/1105748/stories/165268166

Print reports for other dates platform changes

---

csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingFolioSvc.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/GroupBookingFolioSvcGrpc.cs
proto/folio/rpc/group_booking_folio_svc.proto

test cases at : https://centricconsultingllc-my.sharepoint.com/:x:/r/personal/saurabh_arora_centricconsulting_com/Documents/R130TestCases.xlsx?d=w0b1198f2ccf246ec9dc3680b998f4977&csf=1&e=7FHyUW

updated to fetch authorization amount

---

csharp/HOLMS.Platform/HOLMS.Platform/Support/DTOBuilders/Supply/RoomTypeBuilder.cs
csharp/HOLMS.Platform/HOLMS.Platform/Types/out/RoomType.cs
proto/supply/room_types/room_type.proto

Room Image and Image Name FIeld added for ROomType

Room Image and Image Name FIeld added for ROomType
